### ISSUE TITLE
how to start an example?

### ISSUE THREAD

**Issue by REZ1DENT3** [garnele007/SwiftOCR#21]
In attempt to start an example the mistake appears

```
dyld: Library not loaded: @rpath/GPUImage.framework/GPUImage
  Referenced from: /private/var/containers/Bundle/Application/97507C02-4AF1-4CE4-9D20-D6ABA8E0B050/SwiftOCR Camera.app/Frameworks/SwiftOCR.framework/SwiftOCR
  Reason: image not found
(lldb) 
```

Help me please to begin to work with this framework.

_El Capitan 10.11.5 (15F34), XCode Version 7.3.1 (7D1014)_

**Comment by garnele007** [comment]
I'm working on fixing this problem right now. I'll inform you when I fixed it.

**Comment by garnele007** [comment]
@REZ1DENT3 I fixed it by adding the GPUImage framework to the Embedded Binaries.

**Comment by nickberry17** [comment]
I am also having this problem.  I have added the GPUImageFramework included in the SwiftOCR Products group to my project's Embedded Binaries, but it still occurs.  Can you please advise?

**Comment by altinselimi** [comment]
Take Photo button doesn't do anything. What about that ?
