### ISSUE TITLE
How can I install SwiftOCR

### ISSUE THREAD

**Issue by RemyDCF** [garnele007/SwiftOCR#25]
Hello,
I opened this issue because I don't know how I can install this library.
Can you help me ?

**Comment by garnele007** [comment]
First you have to drag the framework folder in your project folder. Then select the `SwiftOCR.xcodeproj` and drag it into your project navigator. Do the same thing with the ´GPUImage.xcodeproj´ or `GPUImageMac.xcodeproj` file located under `SwiftOCR/GPUImage-master/framework`.

![bildschirmfoto 2016-05-27 um 18 20 34](https://cloud.githubusercontent.com/assets/9914734/15614368/adaf76e2-2438-11e6-952c-a99bb0ae4469.png)
![bildschirmfoto 2016-05-27 um 18 20 52](https://cloud.githubusercontent.com/assets/9914734/15614367/ad81fa14-2438-11e6-8d67-3e0a7c4cdc7b.png)

After that you have to add SwiftOCR and GPUImage as an embedded binary.

![bildschirmfoto 2016-05-27 um 18 21 21](https://cloud.githubusercontent.com/assets/9914734/15614381/c512848c-2438-11e6-927f-56cc2d9b2343.png)

![bildschirmfoto 2016-05-27 um 18 21 52](https://cloud.githubusercontent.com/assets/9914734/15614396/dde8587e-2438-11e6-8e45-f59c92965304.png)

The only thing left is to import SwiftOCR in the files in which you want to use it.

![bildschirmfoto 2016-05-27 um 18 30 53](https://cloud.githubusercontent.com/assets/9914734/15614456/2d882a1c-2439-11e6-90e6-37dba096112d.png)

**Comment by RemyDCF** [comment]
Thanks

**Comment by maccesch** [comment]
This is a great guide. Would you mind putting this into the README?

**Comment by ban9ban3** [comment]
I can't install SwiftOCR in xcode 8. Any help? Thanks.

**Comment by toddwilson7** [comment]
Try this this:

Import Swift OCR

First you have to drag the framework folder in your project folder. Then select theSwiftOCR.xcodeproj and drag it into your project navigator. Do the same thing with the ´GPUImage.xcodeproj´ or GPUImageMac.xcodeproj file located under SwiftOCR/GPUImage-master/framework.



After that you have to add SwiftOCR and GPUImage as an embedded binary.


The only thing left is to import SwiftOCR in the files in which you want to use it.

First you have to drag the framework folder in your project folder. Then select theSwiftOCR.xcodeproj and drag it into your project navigator. Do the same thing with the ´GPUImage.xcodeproj´ or GPUImageMac.xcodeproj file located under SwiftOCR/GPUImage-master/framework.



After that you have to add SwiftOCR and GPUImage as an embedded binary.


The only thing left is to import SwiftOCR in the files in which you want to use it.

**Comment by ban9ban3** [comment]
I allready do that
![screen shot 2016-11-16 at 9 59 20 am](https://cloud.githubusercontent.com/assets/10986151/20333223/abad97ec-abe3-11e6-8180-dcb77ab0d5d1.png)



 but get this error:

![screen shot 2016-11-16 at 9 59 04 am](https://cloud.githubusercontent.com/assets/10986151/20333190/840564cc-abe3-11e6-80d1-8c4e5be29693.png)

**Comment by billysoboles2** [comment]
Something has gone badly wrong with either these instructions or the code, I have tried to install this with all sorts of different configurations, dragging the frameworks folder to finder folder of the project, dragging to Xcode above and below folder, into and out of here there and everywhere, dragging xcodeproj' s here there and everywhere and the least errors I can get is 2, the most is about 300.....When it's down to 2 they are: -  warning: using 'ALWAYS_SEARCH_USER_PATHS = YES' while building targets which define modules ('DEFINES_MODULE = YES') may fail. Please migrate to using 'ALWAYS_SEARCH_USER_PATHS = NO'. -----   and ----- “Use Legacy Swift Language Version” (SWIFT_VERSION) is required to be configured correctly for targets which use Swift. Use the [Edit > Convert > To Current Swift Syntax…] menu to choose a Swift version or use the Build Settings editor to configure the build setting directly. ----- Which I have gone round in circles to try and sort out. Given up after around 7 hours of life wasted... Back to Tesseract.

**Comment by garnele007** [comment]
@billysoboles2 I've just pushed a new SwiftOCR version. Could you please try it again with this newer version?

**Comment by saurabh143** [comment]
I Have tried all the above, tried in xcode 7.3.1 and xcode 8.0 as well.
Still not able to build.
I am getting 158 errors currently in the project.

<img width="257" alt="screen shot 2016-12-16 at 1 27 56 am" src="https://cloud.githubusercontent.com/assets/8200710/21239986/51324d72-c32f-11e6-8361-bbc760be6f07.png">

**Comment by EkambaramE** [comment]
I'm also having the same problem to integrate SwiftOCR someone guide me to integrate into  Xcode 8.2

![screen shot 2017-01-09 at 11 01 15 pm](https://cloud.githubusercontent.com/assets/11871096/21776288/d1e3beb2-d6bf-11e6-98f5-56db51d7f67a.png)
![screen shot 2017-01-09 at 11 01 26 pm](https://cloud.githubusercontent.com/assets/11871096/21776289/d1e5eda4-d6bf-11e6-8999-190a6f979838.png)

**Comment by saurabh-360** [comment]
# SwiftOCR-8.2

## Steps to start

1. Make a new project in Xcode 8.2
2. Copy the frameworks folder from this repository, or from the original repo you find here https://github.com/garnele007/SwiftOCR.

<img width="1151" alt="Framework" src="https://cloud.githubusercontent.com/assets/19552394/21780007/fafb0886-d6cf-11e6-84b0-064e768564bd.png">

3. Paste it in your projct folder(right where you find the .xcodeproj file).


4. Go inside the frameworks folder, you will find three files

```
1. SwiftOCR.xcodeproj 
2. SwiftOCR(folder)
3. SwiftOCRTests(folder)
```
 
## Building the project with SwiftOCR
1. Drag and drop the **SwiftOCR.xcodeproj** file into your project inside the project (Make sure you do not create the workspace, this happens if you drop the file outside the project)

![pasteswiftocr](https://cloud.githubusercontent.com/assets/19552394/21780427/8ba59904-d6d1-11e6-86e0-13d012c49963.png)

2. Now go to **frameworks->SwiftOCR->GPUImage-master->framework**, you will find **GPUImage.xcodeproj** there.
3. Drag and drop this file too into the project.
![gpuimagepaste](https://cloud.githubusercontent.com/assets/19552394/21780436/910b43b2-d6d1-11e6-9719-cf34ffb9ed5a.png)


## The tricky part, Adding frameworks
1. Go to **targets->General** scroll down to Embedded Binaries
2. Click +Add
3. Type **GPUImage.framework**, select the one that is outside the scope of you project (having iOS)

![selectgpuimage](https://cloud.githubusercontent.com/assets/19552394/21780444/9934fe48-d6d1-11e6-8136-2ec68ac732b0.png)

4. Click +Add again, and type **Swiftocr.framework**, and select again the one with iOS.

![selectswiftocr](https://cloud.githubusercontent.com/assets/19552394/21780454/a0844d7a-d6d1-11e6-91a7-f9d904b99a59.png)

5. **import SwiftOCR** in before using it.
6. That's all, you will be able to build

I have successfully build a project, you can refer my repo

**Comment by saurabh-360** [comment]
[ExampleSwiftOCR 2.zip](https://github.com/garnele007/SwiftOCR/files/695470/ExampleSwiftOCR.2.zip)

You didn't put the framework folder inside your app's folder.
Before adding the reference, i have added the **framework folder** and it worked.
**framework folder
framework foldrer**

You missed step 2 in the solution i gave.

**Comment by Klavar** [comment]
Hi, is there a way to detect spaces with swift ocr, I am using at at the moment and it doesn't add spaces and also cannot find 1 in the text.

**Comment by adavidov972** [comment]
I'm getting this error while importing Swiftocr -> "Cannot load module 'SwiftOcr' as 'SwiftOCR'"

**Comment by KingGit108** [comment]
I can't fix these errors
 -SwiftOCRTraining.swift:101:21: Use of unresolved identifier 'zonefont'
 -SwiftOCRTraining.swift:130:40: Cannot invoke 'draw' with an argument list of type '(in: CGRect, withAttributes: [NSAttributedStringKey : Any])'

I tried a lot to fix the error on Xcode9.1 beta.
Help me.
